name: CI
on: 
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Use NodeJS
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "17.9.0"
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true      